{{- if .Values.metrics.prometheusOperator }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "stardog.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "stardog.name" . }}
    helm.sh/chart: {{ include "stardog.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "stardog.name" . }}
  endpoints:
  - port: metrics
    interval: 1s
    scrapeTimeout: 30s
  jobLabel: app.kubernetes.io/instance
  podTargetLabels:
    - app.kubernetes.io/component
    - app.kubernetes.io/name
{{- end }}
