apiVersion: v2
description: Kubernetes and OpenShift Backup Operator based on restic
name: k8up
home: https://k8up.io/
keywords:
  - backup
  - operator
  - restic
version: 1.0.3
appVersion: v1.0.2
sources:
  - https://github.com/vshn/k8up
  - https://github.com/vshn/wrestic
maintainers:
  - name: APPUiO Team
    email: info@appuio.ch
