---
# Default values for stardog.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## If the replicaCount is larger than 3 make sure to enable the ZooKeeper chart
replicaCount: 3

image:
  repository: stardog
  registry: stardog-eps-docker.jfrog.io
  # username:
  # password:
  tag: 7.4.2
  pullPolicy: IfNotPresent
  # existingPullSecret: my-image-pull-secret

# nameOverride: ""
# fullnameOverride: ""

stardog:
  adminPassword:
  users:
  # - name: nameOfTheUser
  #   password: passwordForTheUser
  disabledUsers:
  - anonymous
  databases:
  # - name: stardog
  #   options:
  #   - name: search.enabled
  #     value: "true"
  roles:
  - name: superuser
    grants:
    - action: all
      object: "*:*"
    users:
  existingLicenseSecret: stardog-license
  # Custom Stardog config (string value)
  config: |
  javaArgs: -Xmx3g -Xms1g -XX:MaxDirectMemorySize=3g
  backup:
    databases: # List of databases to backup
     # - name: myDB
     #   schedule: "18 03 * * *" # in UTC
    s3Region: eu-central-1
    s3Endpoint:
    s3BucketName:
    s3PathPrefix: # defaults to full name
    s3AccessKey:
    s3SecretKey:
    s3CredentialsExistingSecret: # your existing secret
  securityContext:
    runAsUser: 32541
    fsGroup: 32541
    runAsNonRoot: true

ingress:
  enabled: false

  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    # ingress.kubernetes.io/affinity: cookie

  ## Host for the ingress
  host: stardog.example.com

  ## TLS configuration
  tls:
    enabled: true
    secretName: # tls-stardog

persistence:
  enabled: true
  size: 5Gi
  # storageClass: -

metrics:
  enabled: false
  prometheusOperator: false
  image:
    registry: docker.io
    repository: sscaling/jmx-prometheus-exporter
    tag: 0.12.0
    pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 4000m
    memory: 6.5Gi

nodeSelector: {}

tolerations: []

affinityTopologyKey: kubernetes.io/hostname

# Only applies when stardog's replicaCount is >= 2
zookeeper:
  enabled: true
  replicaCount: 3
  updateStrategy: OnDelete
  allowAnonymousLogin: false
  auth:
    enabled: true
    clientUser: stardogClient
    # clientPassword: secretPassword
    serverUsers: zookeeperServer,
    # serverPasswords: secretPassword,
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - stardog
          topologyKey: kubernetes.io/hostname
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                - zookeeper
          topologyKey: kubernetes.io/hostname
