{{- if eq .Values.haproxy.config "redisk8s"}}
{{- $redisk8s := .Values.haproxy.redisk8s -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "haproxy.fullname" . }}-redisk8s"
  labels:
    app.kubernetes.io/name: {{ include "haproxy.name" . }}
    helm.sh/chart: {{ include "haproxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  haproxy.cfg: |
    global
      log stdout format raw local0
    {{ include "haproxy.resolversConfig" . | nindent 4 }}

    defaults
      log global

      option dontlognull
      timeout connect {{ $redisk8s.timeout.connect }}
      timeout client {{ $redisk8s.timeout.client }}
      timeout server {{ $redisk8s.timeout.client }}

    {{- include "haproxy.metricsConfig" . | nindent 4 }}

    frontend redis
      bind *:{{ .Values.haproxy.frontendPort }}
      mode tcp
      option tcplog
      option clitcpka
      default_backend redis-nodes

    {{- include "haproxy.redisMetricsConfig" . | nindent 4 }}

    backend redis-nodes
      mode tcp

      {{- if $redisk8s.check.enabled }}
      option tcp-check
      tcp-check connect {{ if $redisk8s.tls }} ssl {{ end }}

      {{- if or ($redisk8s.check.redis.auth) ( .Values.haproxy.check.existingSecret) }}
      tcp-check send AUTH\ "${CHECK_AUTH_CREDENTIALS}"\r\n
      tcp-check expect string +OK
      {{- end }}

      tcp-check send PING\r\n
      tcp-check expect string +PONG

      tcp-check send info\ replication\r\n
      tcp-check expect string role:master

      tcp-check send QUIT\r\n
      tcp-check expect string +OK
      {{- end }}

      server-template redis- {{ $redisk8s.nodeCount }} {{ $redisk8s.dnsservicename }}:{{ default "6379" $redisk8s.port }} {{ if $redisk8s.check.enabled }}check inter 1s on-marked-down shutdown-sessions {{ end }}resolvers mydns init-addr none {{ if $redisk8s.tls }} verify none {{ end }}
{{- end }}
