{{- if eq .Values.haproxy.config "galerak8s"}}
{{- $galera := .Values.haproxy.galerak8s -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "haproxy.fullname" . }}-galerak8s"
  labels:
    app.kubernetes.io/name: {{ include "haproxy.name" . }}
    helm.sh/chart: {{ include "haproxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  haproxy.cfg: |
    global
      log stdout format raw local0
      external-check # required for mysql-check
      insecure-fork-wanted # required for mysql-check
    {{- include "haproxy.resolversConfig" . | nindent 4 }}

    defaults
      log global

      option dontlognull
      timeout connect {{ $galera.timeout.connect }}
      timeout client {{ $galera.timeout.client }}
      timeout server {{ $galera.timeout.client }}

    {{- include "haproxy.metricsConfig" . | nindent 4 }}

    frontend galera-in
      bind *:{{ .Values.haproxy.frontendPort }}
      mode tcp
      option tcplog
      option clitcpka
      default_backend galera-nodes

    {{- include "haproxy.galerak8sMetricsConfig" . | nindent 4 }}

    backend galera-nodes
      mode tcp
      option srvtcpka
      option external-check
      external-check command /var/lib/haproxy/script.sh
      balance {{ $galera.balance }}

      {{ if and $galera.check.enabled $galera.check.mysql.enabled }}option mysql-check user {{ $galera.check.mysql.user }}{{ end }}
      server-template node- {{ $galera.nodeCount}} {{ $galera.dnsservicename}}:{{ default "3306" $galera.port }} {{ if $galera.check.enabled }}check {{ end }}resolvers mydns init-addr none
{{- end }}
