kind: ConfigMap
apiVersion: v1
data:
  script.sh: "#!/bin/bash\n\n# Run the MySQL query and store the result in a Bash
    variable\nwsrep_ready=$(/bin/cat /secrets/mariadb-root-password | /usr/bin/mysql
    -h $3 -u root -p -e \"SELECT VARIABLE_VALUE FROM information_schema.global_status
    WHERE VARIABLE_NAME = 'wsrep_ready';\" -N)\nif [ \"$?\" -ne 0 ]; then\n  echo
    \"Error: Unable to connect to MySQL or query failed\"\n  exit 1\nfi\n\nif [ \"$wsrep_ready\"
    != \"ON\" ]; then\n  echo \"Error: wsrep_ready is not ON, actual status is: $WSREP_READY\"\n
    \ exit 1\nfi\n\nexit 0 \n"