apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "haproxy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "haproxy.name" . }}
    helm.sh/chart: {{ include "haproxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "haproxy.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "haproxy.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/configmap: {{ include (print .Template.BasePath "/configmap-" .Values.haproxy.config ".yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: CHECK_AUTH_CREDENTIALS
            valueFrom:
              secretKeyRef:
                name: {{ if not (empty .Values.haproxy.check.existingSecret.name) }}{{ .Values.haproxy.check.existingSecret.name}}{{ else }}{{ include "haproxy.fullname" . }}-check-auth {{ end }}
                key: {{ if not (empty .Values.haproxy.check.existingSecret.name) }}{{ .Values.haproxy.check.existingSecret.key}}{{ else }}auth-credentials{{ end }}
                optional: true
          ports:
            - name: frontend
              containerPort: {{ .Values.haproxy.frontendPort }}
              protocol: TCP
            {{- if .Values.metrics.enabled }}
            - name: metrics
              containerPort: 9000
            {{- end }}
            {{- if or .Values.haproxy.redisk8s.metrics.enabled .Values.haproxy.galerak8s.metrics.enabled .Values.haproxy.galera.metrics.enabled .Values.haproxy.mariadbOperator.metrics.enabled}}
            - name: metrics-backend
              containerPort: 9090
            {{- end }}
          readinessProbe:
          {{- if .Values.metrics.enabled }}
            httpGet:
              path: /healthz
              port: metrics
          {{- else }}
            tcpSocket:
              port: frontend
          {{- end }}
            initialDelaySeconds: 3
          livenessProbe:
          {{- if .Values.metrics.enabled }}
            httpGet:
              path: /healthz
              port: metrics
          {{- else }}
            tcpSocket:
              port: frontend
          {{- end }}
            initialDelaySeconds: 120
            periodSeconds: 20
            timeoutSeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: haproxy-config
              mountPath: /etc/haproxy/
            {{- if or (eq .Values.haproxy.config "galera") (eq .Values.haproxy.config "galerak8s") (eq .Values.haproxy.config "mariadb-operator") }}
            - mountPath: /var/lib/haproxy
              name: haproxy-script
            - mountPath: /secrets
              name: mariadb-creds
            {{ end }}
      {{- if .Values.sidecarContainers }}
{{ tpl (toYaml .Values.sidecarContainers) . | indent 8 }}
      {{- end }}
      volumes:
        - name: haproxy-config
          configMap:
            name: "{{ include "haproxy.fullname" . }}-{{ .Values.haproxy.config }}"
       {{- if or (eq .Values.haproxy.config "galera") (eq .Values.haproxy.config "galerak8s") (eq .Values.haproxy.config "mariadb-operator") }}
        - name: haproxy-script
          configMap:
            # it's 0555 read+execute permissions
            defaultMode: 365
            name: haproxy-script
        - name: mariadb-creds
          secret:
            secretName: mariadb
            defaultMode: 420
        {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity: {{- tpl (toYaml .) $ | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.haproxy.securityContext }}
      securityContext: {{ . | toYaml | nindent 8 }}
    {{- end }}
