dependencies:
  - name: redis
    version: 16.10.1
    # Pinned to index.yaml before upstream cleanup (see: https://github.com/bitnami/charts/pull/10530)
    repository: https://raw.githubusercontent.com/bitnami/charts/defb094c658024e4aa8245622dab202874880cbc/bitnami/
    condition: redis.enabled
