dependencies:
  - name: zookeeper
    version: 9.2.7
    repository: https://raw.githubusercontent.com/bitnami/charts/b661ad0e6e3277fc5b5b2db197cba47174693712/bitnami/
    condition: zookeeper.enabled
