dependencies:
  - name: zookeeper
    version: 5.23.0
    # Pinned to index.yaml before upstream cleanup (see: https://github.com/bitnami/charts/pull/10530)
    repository: https://raw.githubusercontent.com/bitnami/charts/defb094c658024e4aa8245622dab202874880cbc/bitnami/
    condition: zookeeper.enabled
