{{- if .Values.stardog.backup.databases }}
{{- if not .Values.stardog.backup.s3CredentialsExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stardog.fullname" . }}-backup-s3-credentials
  labels:
    app.kubernetes.io/name: {{ include "stardog.name" . }}
    helm.sh/chart: {{ include "stardog.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  s3-access-key: {{ required "An access key is required to make backups" .Values.stardog.backup.s3AccessKey | b64enc | quote }}
  s3-secret-key: {{ required "A secret key is required to make backups" .Values.stardog.backup.s3SecretKey | b64enc | quote }}
{{- end }}
{{- end }}
