{{ if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
{{ if .Values.route.annotations }}
  annotations:
{{ toYaml .Values.route.annotations | indent 4 }}
{{ end }}
  labels:
    app: {{ template "openshift-oauth-proxy.name" $ }}
    chart: {{ template "openshift-oauth-proxy.chart" $ }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "openshift-oauth-proxy.fullname" $ }}
spec:
{{ if .Values.route.host }}
  host: {{ .Values.route.host }}
{{ end }}
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ template "openshift-oauth-proxy.fullname" $ }}
    weight: 100
  wildcardPolicy: None
  {{ if .Values.route.tls }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  {{ end }}
{{ end }}
