apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "openshift-oauth-proxy.name" $ }}
    chart: {{ template "openshift-oauth-proxy.chart" $ }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "openshift-oauth-proxy.fullname" $ }}
type: Opaque
data:
  cookie-secret: {{ randAlphaNum 32 | b64enc | quote }}
