apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "openshift-oauth-proxy.fullname" $ }}
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.alertmanager-main: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"{{ template "openshift-oauth-proxy.fullname" $ }}"}}'
