{{- if and .Values.sentinel.enabled .Values.sentinel.forceUpdate }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ printf "%s-sts-deleter" (include "common.names.fullname" .) }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-6"
  labels:
    app: {{ template "redis.name" . }}
    chart: {{ template "redis.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ printf "%s-sts-deleter" (include "common.names.fullname" .) }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-6"
  labels:
    app: {{ template "redis.name" . }}
    chart: {{ template "redis.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups: ["", "apps"]
    resources: ["statefulsets"]
    verbs: ["delete", "get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "%s-sts-deleter" (include "common.names.fullname" .) }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-6"
  labels:
    app: {{ template "redis.name" . }}
    chart: {{ template "redis.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  kind: Role
  name: {{ printf "%s-sts-deleter" (include "common.names.fullname" .) }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ printf "%s-sts-deleter" (include "common.names.fullname" .) }}
    namespace: "{{ .Release.Namespace }}"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-sts-deleter" (include "common.names.fullname" .) }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    app: {{ template "redis.name" . }}
    chart: {{ template "redis.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  # Don't retry
  backoffLimit: 0
  template:
    metadata:
      name: {{ printf "%s-sts-deleter" (include "common.names.fullname" .) }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ printf "%s-sts-deleter" (include "common.names.fullname" .) }}
      containers:
        - name: pre-upgrade-delete-sts
          image: {{ .Values.sentinel.forceUpdateKubectlImage }}
          command: [ "/bin/bash", "/scripts/delete.sh" ]
          volumeMounts:
            - name: scripts
              mountPath: /scripts/
      volumes:
        - name: scripts
          configMap:
            name: {{ printf "%s-sts-deleter" (include "common.names.fullname" .) }}
            defaultMode: 0755
{{- end }}
