{{- $endpoint := .Values.trifid.sparql.endpoint -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trifid.fullname" . }}
  labels:
    {{- include "trifid.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "trifid.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "trifid.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "trifid.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: SPARQL_ENDPOINT_URL
            value: {{ $endpoint.url }}
          - name: SPARQL_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ if $endpoint.secretName }}{{ $endpoint.secretName }}{{ else }}{{ include "trifid.fullname" . }}{{ end }}
                key: username
          - name: SPARQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ if $endpoint.secretName }}{{ $endpoint.secretName }}{{ else }}{{ include "trifid.fullname" . }}{{ end }}
                key: password
          {{- range $key, $value := .Values.extraEnv }}
          - name: {{ $key }}
            value: {{ $value }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - "{{ include "trifid.name" . }}"
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - "{{ .Release.Name }}"
              topologyKey: kubernetes.io/hostname
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
