{{- if .Values.forceUpdate }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ printf "%s-sts-deleter" (include "common.names.fullname" .) }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-6"
  labels: {{- include "common.labels.standard" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ printf "%s-sts-deleter" (include "common.names.fullname" .) }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-6"
  labels: {{- include "common.labels.standard" . | nindent 4 }}
rules:
  - apiGroups: ["", "apps"]
    resources: ["statefulsets"]
    verbs: ["delete", "get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "%s-sts-deleter" (include "common.names.fullname" .) }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-6"
  labels: {{- include "common.labels.standard" . | nindent 4 }}
roleRef:
  kind: Role
  name: {{ printf "%s-sts-deleter" (include "common.names.fullname" .) }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ printf "%s-sts-deleter" (include "common.names.fullname" .) }}
    namespace: "{{ .Release.Namespace }}"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-sts-deleter" (include "common.names.fullname" .) }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  backoffLimit: 3
  template:
    metadata:
      name: {{ printf "%s-sts-deleter" (include "common.names.fullname" .) }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ printf "%s-sts-deleter" (include "common.names.fullname" .) }}
      containers:
        - name: pre-upgrade-delete-sts
          image: {{ .Values.forceUpdateKubectlImage }}
          command: [ "/bin/bash", "/scripts/delete.sh" ]
          volumeMounts:
            - name: scripts
              mountPath: /scripts/
      volumes:
        - name: scripts
          configMap:
            name: {{ printf "%s-sts-deleter" (include "common.names.fullname" .) }}
            defaultMode: 0755
{{- end }}
