---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "rabbitmq.fullname" . }}-discovery
  labels:
    app: {{ template "rabbitmq.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  clusterIP: None
  ports:
    - name: epmd
      port: 4369
    - name: management
      port: 15672
    - name: amqp
      port: 5672
  selector:
    app: rabbitmq

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "rabbitmq.fullname" . }}
  labels:
    app: {{ template "rabbitmq.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
    - name: epmd
      port: 4369
    - name: management
      port: 15672
    - name: amqp
      port: 5672
  selector:
    app: rabbitmq
