apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "stardog.fullname" . }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "stardog.name" . }}
