{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "maxscale.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "maxscale.name" . }}
    helm.sh/chart: {{ include "maxscale.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  service-password: {{ .Values.servicePassword | b64enc | quote }}
  monitor-password: {{ .Values.monitorPassword | b64enc | quote }}
{{- end -}}
